[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
teloxide = "0.5"  # библиотека для работы с Telegram
dotenv = "0.15"  # для загрузки переменных окружения из .env
